version: '3.8'

services:
  pg:
    image: postgres:17.2-alpine3.21
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - finance-service

  finance-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
      - pg
    networks:
      - finance-service

volumes:
  postgres_volume:

networks:
  finance-service: